FROM microsoft/windowsservercore:1803 as download

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ARG TOMCAT_VERSION="8.5.32"
ENV CATALINA_HOME="c:/apache-tomcat" \
    TOMCAT_DOWNLOAD_URL="https://www.apache.org/dist/tomcat/tomcat-8/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}-windows-x64.zip" \
    TOMCAT_SHA512="01ae78f6497fd214b0bd68d81354230976835fba55f95140c7532fd3a523ad6be3e6b160b311ff8881fbf82cd2954284ede67e70a5d145aea4f61ec83714c158" 

RUN $AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'; \ 
    [System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols; \
    Write-Host ('Downloading {0} ...' -f $env:TOMCAT_DOWNLOAD_URL); \
    $localFileName = 'apache-tomcat-{0}.zip' -f $env:TOMCAT_VERSION; \
    Invoke-WebRequest -Uri $env:TOMCAT_DOWNLOAD_URL -OutFile $localFileName; \
    Write-Host ('Verifying sha512 ({0}) ...' -f $env:TOMCAT_SHA512); \
    if ((Get-FileHash $localFileName -Algorithm sha512).Hash -ne $env:TOMCAT_SHA512) { Write-Host 'FAILED!'; exit 1; }; \
    Write-Host 'Expanding ...'; \
    Expand-Archive -Path $localFileName -DestinationPath 'C:\' ; \ 
    Remove-Item $localFileName;

FROM abezverkov/openjdk-nanoserver:1.8.0

# Dockerfile author / maintainer 
MAINTAINER Adam Bezverkov <adam.bezverkov@gmail.com> 

ARG TOMCAT_VERSION="8.5.32"
ENV CATALINA_HOME="c:/apache-tomcat" \
    TOMCAT_NATIVE_LIBDIR="$CATALINA_HOME/native-jni-lib" \
    LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$TOMCAT_NATIVE_LIBDIR"

COPY --from=download c:/apache-tomcat-$TOMCAT_VERSION $CATALINA_HOME

USER Administrator

RUN setx /M PATH "c:/apache-tomcat/bin;%PATH%"

WORKDIR $CATALINA_HOME/bin

EXPOSE 8080

CMD ["catalina.bat","run"]