FROM microsoft/windowsservercore:1803 as download

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV JAVA_HOME C:\\ojdkbuild
# https://github.com/ojdkbuild/ojdkbuild/releases
ENV JAVA_VERSION=8u171 \
    JAVA_OJDKBUILD_VERSION=-1.8.0.171-1 \
    JAVA_OJDKBUILD_ZIP=java-1.8.0-openjdk-1.8.0.171-1.b10.ojdkbuild.windows.x86_64.zip \
    JAVA_OJDKBUILD_SHA256=35104f658ed51d1b24cf6f0f6d1d21524d7640d3e3e7b64d8d7ac86cbfbc2ab9

COPY ${JAVA_OJDKBUILD_ZIP} ojdkbuild.zip

RUN $AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'; \ 
    [System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols; \
    #$url = ('https://github.com/ojdkbuild/ojdkbuild/releases/download/{0}/{1}' -f $env:JAVA_OJDKBUILD_VERSION, $env:JAVA_OJDKBUILD_ZIP); \
    #Write-Host ('Downloading {0} ...' -f $url); \
    #Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile 'ojdkbuild.zip'; \
    Write-Host ('Verifying sha256 ({0}) ...' -f $env:JAVA_OJDKBUILD_SHA256); \
    if ((Get-FileHash ojdkbuild.zip -Algorithm sha256).Hash -ne $env:JAVA_OJDKBUILD_SHA256) { \
        Write-Host 'FAILED!'; \
        exit 1; \
    }; \
    \
    Write-Host 'Expanding ...'; \
    Expand-Archive ojdkbuild.zip -DestinationPath C:\; \
    \
    Write-Host 'Renaming ...'; \
    Move-Item \
        -Path ('C:\{0}' -f ($env:JAVA_OJDKBUILD_ZIP -Replace '.zip$', '')) \
        -Destination $env:JAVA_HOME \
    ; \
    \
    $env:PATH = 'C:\ojdkbuild\bin;' + $env:PATH; \
    Write-Host 'Verifying install ...'; \
    Write-Host '  java -version'; java -version; \
    Write-Host '  javac -version'; javac -version; \
    \
    Write-Host 'Removing ...'; \
    Remove-Item ojdkbuild.zip -Force; \
    \
    Write-Host 'Complete.';

FROM microsoft/nanoserver:1803

ENV JAVA_HOME=C:/ojdkbuild \
    JAVA_VERSION=8u171 \
    JAVA_OJDKBUILD_VERSION=-1.8.0.171-1 \
    JAVA_OJDKBUILD_ZIP=java-1.8.0-openjdk-1.8.0.171-1.b10.ojdkbuild.windows.x86_64.zip \
    JAVA_OJDKBUILD_SHA256=35104f658ed51d1b24cf6f0f6d1d21524d7640d3e3e7b64d8d7ac86cbfbc2ab9

COPY --from=download C:/ojdkbuild C:/ojdkbuild

USER Administrator

RUN setx /M PATH "C:\ojdkbuild\bin;%PATH%"
