FROM microsoft/windowsservercore:1803 as download

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ARG MONGO_VERSION=3.6.5 
ENV MONGO_VERSION=${MONGO_VERSION}  \
    MONGO_DOWNLOAD_URL=http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-${MONGO_VERSION}.zip \
    MONGO_DOWNLOAD_SHA256=3546f8d5721e91c9158133d37335d35703207af566266b248eeba6ed0db0fbc0

RUN Write-Host ('Downloading {0} ...' -f $env:MONGO_DOWNLOAD_URL); \
    Invoke-WebRequest -Uri $env:MONGO_DOWNLOAD_URL -OutFile 'mongodb.zip'; \
    Write-Host ('Verifying sha256 ({0}) ...' -f $env:MONGO_DOWNLOAD_SHA256); \
    if ((Get-FileHash mongodb.zip -Algorithm sha256).Hash -ne $env:MONGO_DOWNLOAD_SHA256) { Write-Host 'FAILED!'; exit 1; }; \
    Expand-Archive mongodb.zip -DestinationPath C: ; \
    Remove-Item mongodb.zip ; \
    # \
    Write-Host ('Downloading Visual C++ Redistributable Package'); \
    Invoke-WebRequest -Uri https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe -OutFile vcredist.exe; \
    Start-Process .\vcredist.exe -ArgumentList '/install', '/quiet', '/norestart' -NoNewWindow -Wait ; \
    Remove-Item vcredist.exe ; \
    # \
    Write-Host ('Preparing one folder for final COPY deployment into NanoServer'); \
    mkdir C:/prepare | Out-Null ; \
    cp C:/windows/system32/msvcp140.dll C:/prepare ; \
    cp C:/windows/system32/vccorlib140.dll C:/prepare ; \
    cp C:/windows/system32/vcruntime140.dll C:/prepare ; \
    cp C:/mongodb-win32-x86_64-2008plus-ssl-$env:MONGO_VERSION/bin/*.dll C:/prepare ; \
    cp C:/mongodb-win32-x86_64-2008plus-ssl-$env:MONGO_VERSION/bin/*.exe C:/prepare ; 
    
    #ren C:/mongodb-win32-x86_64-2008plus-ssl-$env:MONGO_VERSION C:/mongodb ;

FROM microsoft/nanoserver:1803

COPY --from=download C:/prepare C:/windows/system32

USER Administrator

RUN setx /M PATH "C:\mongodb\bin;%PATH%"

VOLUME C:/data/db C:/data/configdb C:/data/log

EXPOSE 27017

CMD ["mongod.exe","--bind_ip_all"]